package test

import (
	"context"
	"os"
	"testing"

	"github.com/cucumber/godog"
	"github.com/lukasngl/godogen/test/steps"
)

func TestFeatures(t *testing.T) {
	suite := godog.TestSuite{
		ScenarioInitializer: InitializeScenario,
		Options: &godog.Options{
			Format:   "pretty",
			Paths:    []string{"features"},
			TestingT: t,
			Strict:   true,
		},
	}

	if suite.Run() != 0 {
		t.Fatal("non-zero status returned, failed to run feature tests")
	}
}

func InitializeScenario(sc *godog.ScenarioContext) {
	tc, err := steps.NewTestContext()
	if err != nil {
		panic(err)
	}

	sc.After(func(ctx context.Context, sc *godog.Scenario, scenarioErr error) (context.Context, error) {
		if scenarioErr != nil {
			// Print normalized output on failure for debugging
			if output := tc.GetNormalizedOutput(); output != "" {
				println("\n=== Normalized command output ===")
				println(output)
				println("=================================")
			}
		}
		tc.Cleanup()
		return ctx, nil
	})

	// Register steps - generated by godogen
	steps.InitializeFileSteps(sc, tc)
	steps.InitializeGodogenSteps(sc, tc)
	steps.InitializeAssertionSteps(sc, tc)
}

func TestMain(m *testing.M) {
	os.Exit(m.Run())
}
