package main

import (
	"flag"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"

	"github.com/iancoleman/strcase"
)

// See https://go.dev/blog/generate
const initializerTpl = `// Code generated by godogen; DO NOT EDIT."

package {{.Package}}

import "github.com/cucumber/godog"

// Initialize{{.Name}} registers steps defined in "{{ .Filepath }}" with the [godog.ScenarioContext].
func Initialize{{.Name}}(ctx *godog.ScenarioContext) {
	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
	// of the respective function declaration.
	//
	// Note: there must be no space between the "//" and the "godogen:step",
	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
{{- range .Before }}
	ctx.Before({{.}})
{{- end }}
{{- range .After }}
	ctx.After({{.}})
{{- end }}
{{- range .Steps }}
	ctx.{{.Type}}(` + "`{{.Pattern}}`" + `, {{.Function}})
{{- end }}
}
`

var tmpl = template.Must(template.New("").Parse(initializerTpl))

var (
	input        = flag.String("input", "./", "input file of package")
	outputSuffix = flag.String("suffix", "_initialize.go", "suffix to append to input filename")
)

type (
	File struct {
		Filepath      string
		Package       string
		Name          string
		Steps         []Step
		Before, After []string

		// To lookup token locations
		fset *token.FileSet
	}
	Step struct {
		// One of "Step", "Given", "When", or "Then"
		Type     string
		Pattern  string
		Function string
	}
)

func main() {
	fset := token.NewFileSet()

	if strings.HasSuffix(*input, ".go") {
		goFile, err := parser.ParseFile(fset, *input, nil, parser.ParseComments)
		if err != nil {
			log.Fatalf("failed to parse lol")
		}

		err = genFile(fset, *input, goFile)
		if err != nil {
			log.Fatalf("failed to generate initializer for %q: %v", *input, err)
		}
	} else {
		pkgs, err := parser.ParseDir(fset, *input, nil, parser.ParseComments)
		if err != nil {
			log.Fatalf("failed to parse lol")
		}

		for _, pkg := range pkgs {
			for filenpath, goFile := range pkg.Files {
				err = genFile(fset, filenpath, goFile)
				if err != nil {
					log.Fatalf("failed to generate initializer for %q: %v", *input, err)
				}
			}
		}
	}
}

func genFile(fset *token.FileSet, filenpath string, goFile *ast.File) error {
	slug := filepath.Base(filenpath)
	slug = strings.TrimSuffix(slug, ".go")

	file := &File{
		Filepath: filenpath,
		Package:  goFile.Name.Name,
		Name:     strcase.ToCamel(slug),
		fset:     fset,
	}

	ast.Walk(file, goFile)

	if len(file.Steps)+len(file.After)+len(file.Before) == 0 {
		return nil
	}

	outfile, err := os.Create(slug + *outputSuffix)
	if err != nil {
		log.Fatalf("%s: failed to open output file: %v", filenpath, err)
	}

	err = tmpl.Execute(outfile, file)
	if err != nil {
		log.Fatalf("%s: failed to render template: %v", filenpath, err)
	}

	return nil
}

// Visit implements ast.Visitor.
func (file *File) Visit(node ast.Node) (w ast.Visitor) {
	switch node := node.(type) {
	case nil:
		return nil
	case *ast.FuncDecl:
		if node.Doc == nil {
			break
		}

		funname := node.Name.Name

		for _, comment := range node.Doc.List {
			directive, isDirective := strings.CutPrefix(comment.Text, "//godogen:")
			if !isDirective {
				continue
			}

			parts := strings.SplitN(directive, " ", 2)
			directive = parts[0]

			switch directive {
			case "before":
				file.Before = append(file.Before, funname)
				return file

			case "after":
				file.After = append(file.After, funname)
				return file

			case "step", "given", "when", "then":
				if len(parts) == 1 {
					log.Printf("WARN step %q at %s is missing the pattern",
						funname, file.fset.Position(comment.Pos()),
					)
				}

				pattern := parts[1]

				_, err := regexp.Compile(pattern)
				if err != nil {
					log.Printf("WARN step %q at %s has invalid regex: %v",
						funname, file.fset.Position(comment.Pos()), err,
					)
				}

				file.Steps = append(file.Steps, Step{
					Type:     strcase.ToCamel(directive),
					Pattern:  pattern,
					Function: funname,
				})

			default:
				log.Printf("WARN decl %q at %s has unknown directive %q",
					funname, file.fset.Position(comment.Pos()), directive,
				)

				return file
			}
		}
	}

	return file
}
