package main

import (
	"flag"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"

	"github.com/iancoleman/strcase"
)

// See https://go.dev/blog/generate
const initializerTpl = `// Code generated by godogen; DO NOT EDIT."

package {{.Package}}

import "github.com/cucumber/godog"

// Initialize{{.Name}} registers steps defined in "{{ .Filepath }}" with the [godog.ScenarioContext].
func Initialize{{.Name}}(ctx *godog.ScenarioContext) {
	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
	// of the respective function declaration.
	//
	// Note: there must be no space between the "//" and the "godogen:step",
	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
{{- range .Before }}
	ctx.Before({{.}})
{{- end }}
{{- range .After }}
	ctx.After({{.}})
{{- end }}
{{- range .Steps }}
	ctx.{{.Type}}(` + "`{{.Pattern}}`" + `, {{.Function}})
{{- end }}
}
`

var (
	input         = flag.String("input", "./", "input file of package")
	outputPatterr = flag.String("suffix", "_initialize.go", "suffix to append to input filename")
)

type (
	File struct {
		Filepath      string
		Package       string
		Name          string
		Steps         []Step
		Before, After []string

		// To lookup token locations
		fset *token.FileSet
	}
	Step struct {
		// One of "Step", "Given", "When", or "Then"
		Type     string
		Pattern  string
		Function string
	}
)

func main() {
	fset := token.NewFileSet()

	tmpl := template.Must(template.New("").Parse(initializerTpl))

	pkgs, err := parser.ParseDir(fset, "./", nil, parser.ParseComments)
	if err != nil {
		log.Fatalf("failed to parse lol")
	}

	for pkgname, pkg := range pkgs {
		for filenpath, goFile := range pkg.Files {
			slug := filepath.Base(filenpath)
			slug = strings.TrimSuffix(slug, ".go")

			file := &File{
				Filepath: filenpath,
				Package:  pkgname,
				Name:     strcase.ToCamel(slug),
				fset:     fset,
			}

			ast.Walk(file, goFile)

			if len(file.Steps)+len(file.After)+len(file.Before) == 0 {
				continue
			}

			outfile, err := os.Create(slug + "_initialize.go")
			if err != nil {
				log.Fatalf("%s: failed to open output file: %v", filenpath, err)
			}

			err = tmpl.Execute(outfile, file)
			if err != nil {
				log.Fatalf("%s: failed to render template: %v", filenpath, err)
			}
		}
	}
}

// Visit implements ast.Visitor.
func (file *File) Visit(node ast.Node) (w ast.Visitor) {
	switch node := node.(type) {
	case nil:
		return nil
	case *ast.FuncDecl:
		if node.Doc == nil {
			break
		}

		funname := node.Name.Name

		for _, comment := range node.Doc.List {
			if comment.Text == "//godogen:before" {
				file.Before = append(file.Before, funname)
				break
			}

			if comment.Text == "//godogen:after" {
				file.After = append(file.After, funname)
				break
			}

			pattern, isStep := strings.CutPrefix(comment.Text, "//godogen:step ")
			if !isStep {
				continue
			}

			_, err := regexp.Compile(pattern)
			if err != nil {
				log.Printf("WARN step %q at %s has invalid regex: %v",
					funname, file.fset.Position(comment.Pos()), err,
				)
			}

			file.Steps = append(file.Steps, Step{
				Type:     stepTypeFrom(funname),
				Pattern:  pattern,
				Function: funname,
			})
		}
	}

	return file
}

func stepTypeFrom(funcName string) string {
	switch {
	case strings.HasPrefix(funcName, "given"):
		return "Given"
	case strings.HasPrefix(funcName, "when"):
		return "When"
	case strings.HasPrefix(funcName, "then"):
		return "Then"
	default:
		return "Step"
	}
}
