// Code generated by godogen; DO NOT EDIT.

package steps

import "github.com/cucumber/godog"

// InitializeAssertionSteps registers steps defined in "assertion_steps.go" with the [godog.ScenarioContext].
func InitializeAssertionSteps(sc *godog.ScenarioContext, r1 *TestContext) {
	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
	// of the respective function declaration.
	//
	// Note: there must be no space between the "//" and the "godogen:step",
	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
	sc.Then(`^the command should succeed$`, r1.theCommandShouldSucceed)
	sc.Then(`^the command should fail$`, r1.theCommandShouldFail)
	sc.Then(`^the command output should be:$`, r1.theCommandOutputShouldBe)
	sc.Then(`^the command output should be empty$`, r1.theCommandOutputShouldBeEmpty)
	sc.Then(`^the command output should contain "([^"]*)"$`, r1.theCommandOutputShouldContain)
	sc.Then(`^the command output should contain:$`, r1.theCommandOutputShouldContainDocstring)
	sc.Then(`^the file "([^"]*)" should exist$`, r1.theFileShouldExist)
	sc.Then(`^the file "([^"]*)" should not exist$`, r1.theFileShouldNotExist)
	sc.Then(`^the file "([^"]*)" should have content:$`, r1.theFileShouldHaveContent)
	sc.Then(`^the file "([^"]*)" should contain:$`, r1.theFileShouldContain)
}
