// Code generated by godogen; DO NOT EDIT.

package steps

import "github.com/cucumber/godog"

// InitializeFileSteps registers steps defined in "file_steps.go" with the [godog.ScenarioContext].
func InitializeFileSteps(sc *godog.ScenarioContext, r1 *TestContext) {
	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
	// of the respective function declaration.
	//
	// Note: there must be no space between the "//" and the "godogen:step",
	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
	sc.Given(`^a Go file "([^"]*)" with content:$`, r1.aGoFileWithContent)
}
