// Code generated by godogen; DO NOT EDIT.

package steps

import "github.com/cucumber/godog"

// InitializeGodogenSteps registers steps defined in "godogen_steps.go" with the [godog.ScenarioContext].
func InitializeGodogenSteps(sc *godog.ScenarioContext, r1 *TestContext) {
	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
	// of the respective function declaration.
	//
	// Note: there must be no space between the "//" and the "godogen:step",
	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
	sc.When(`^I run godogen$`, r1.iRunGodogen)
}
