package main

import (
	"bufio"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"iter"
	"log/slog"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"text/template"

	"github.com/iancoleman/strcase"
	"github.com/lukasngl/godogen"
)

var (
	help         = flag.Bool("help", false, "show help message")
	verbose      = flag.Bool("verbose", false, "enable verbose output")
	input        = flag.String("input", "./", "input file of package")
	outputSuffix = flag.String("suffix", "_initialize.go", "suffix to append to input filename")
	usage        = `godogen scans Go source files for functions with "//godogen:step" directive comments
and generates corresponding godog scenario initializer functions.

Usage:

	godogen [flags]

The flags are:

	-help
	    show this help message
	-input string
	    input file or directory to scan for step definitions (default "./")
	-suffix string
	    suffix to append to input filename for generated files (default "_initialize.go")
	-verbose
	    enable verbose output

Step Definition Format:

To define a step, add a directive comment above your function:

	//godogen:step ^I have (\d+) cucumbers$
	func IHaveCucumbers(count int) error {
	    // implementation
	}

The generated initializer function will register this step with godog:

	func InitializeSteps(sc *godog.ScenarioContext) {
	    sc.Step(r` + "`" + `^I have (\d+) cucumbers$` + "`" + `, IHaveCucumbers)
	}

Note: There must be no space between "//" and "godogen:step" for the directive
to be recognized as per Go's directive comment syntax.

Examples:

	# Generate initializers for all .go files in current directory
	godogen

	# Generate initializer for specific file
	godogen -input steps.go

	# Generate with custom suffix and verbose output
	godogen -suffix "_godog.go" -verbose

Generated files follow Go's code generation conventions and include a header
comment indicating they should not be edited manually.
`
)

// See https://go.dev/blog/generate
const initializerTpl = `// Code generated by godogen; DO NOT EDIT.

package {{.Package}}

import "github.com/cucumber/godog"

// Initialize{{.Name}} registers steps defined in "{{ .Filepath }}" with the [godog.ScenarioContext].
func Initialize{{.Name}}(sc *godog.ScenarioContext
{{- range .StepFuncs.Receivers -}}
	, {{ receiverName . }} {{.TypeName}}
{{- end -}}
) {
	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
	// of the respective function declaration.
	//
	// Note: there must be no space between the "//" and the "godogen:step",
	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
{{- range .StepFuncs }}
{{- $receiver := .Receiver }}
{{- range .Steps }}
	sc.{{.Kind}}(` + "`{{escapeBackticks .Pattern}}`" + `, {{ with $receiver }}{{ receiverName . }}.{{ end }}{{ .Function }})
{{- end }}
{{- range .Hooks }}
	sc.{{.Kind}}({{.Function}})
{{- end }}
{{- range .StepHooks }}
	sc.StepContext().{{.Kind}}({{.Function}})
{{- end }}
{{- end }}
}
`

type File struct {
	Filepath  string
	Package   string
	Name      string
	StepFuncs godogen.StepFuncs
}

func main() {
	flag.Parse()

	if *help {
		_, _ = io.WriteString(flag.CommandLine.Output(), usage)
		os.Exit(0)
	}

	if err := run(); err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}
}

// run executes the main logic of the godogen tool.
func run() error {
	setupLogger(*verbose)

	fset := token.NewFileSet()

	files, err := getFiles(fset, *input)
	if err != nil {
		return err
	}

	hasErr := false
	for filepath, goFile := range files {
		if isGenerated(goFile) {
			continue
		}

		err = genFile(fset, filepath, goFile)
		if err != nil {
			fmt.Println(err.Error())
			hasErr = true
		}
	}

	if hasErr {
		return fmt.Errorf("one or more errors occurred while generating scenario initializers")
	}

	return nil
}

// getFiles returns an iterator over the Go files in the given input path.
func getFiles(fset *token.FileSet, input string) (iter.Seq2[string, *ast.File], error) {
	if strings.HasSuffix(input, ".go") {
		file, err := parser.ParseFile(fset, input, nil, parser.ParseComments)
		if err != nil {
			return nil, err
		}

		return func(yield func(string, *ast.File) bool) {
			yield(input, file)
		}, nil
	} else {
		pkgs, err := parser.ParseDir(fset, input, nil, parser.ParseComments)
		if err != nil {
			return nil, err
		}

		return func(yield func(string, *ast.File) bool) {
			for _, pkg := range pkgs {
				for filepath, file := range pkg.Files {
					if !yield(filepath, file) {
						return
					}
				}
			}
		}, nil
	}
}

// genFile generates a scenario initializer file for the given input file.
func genFile(fset *token.FileSet, path string, input *ast.File) error {
	slug := filepath.Base(path)
	slug = strings.TrimSuffix(slug, ".go")
	slog := slog.With(slog.String("input", path))

	stepFuncs := godogen.GetStepDefinitions(fset, input)

	if len(stepFuncs) == 0 {
		slog.Debug("no steps found, ignoring")
		return nil
	}

	for err := range stepFuncs.ValidationErrors() {
		fmt.Println(prettyPrintValidationErr(fset, err))
	}

	file := &File{
		Filepath:  path,
		Package:   input.Name.Name,
		Name:      strcase.ToCamel(slug),
		StepFuncs: stepFuncs,
	}

	outfile, err := os.Create(slug + *outputSuffix)
	if err != nil {
		return fmt.Errorf("%s: failed to open output file: %v", path, err)
	}

	receiverNames := map[string]string{}
	receiverIdx := 1

	tmpl := template.Must(template.New("").Funcs(template.FuncMap{
		"escapeBackticks": escapeBackticks,
		"receiverName": func(r *godogen.Receiver) string {
			receiverName, ok := receiverNames[r.TypeName]
			if !ok {
				receiverName = fmt.Sprintf("r%d", receiverIdx)
				receiverIdx++
				receiverNames[r.TypeName] = receiverName
			}

			return receiverName
		},
	}).Parse(initializerTpl))

	err = tmpl.Execute(outfile, file)
	if err != nil {
		return fmt.Errorf("%s: failed to render template: %v", path, err)
	}

	slog.Debug(
		"scenario initializer successfully created",
		"output", outfile.Name(),
	)

	return nil
}

// escapeBackticks escapes backticks in the generated go code.
func escapeBackticks(s string) string {
	if !strings.Contains(s, "`") {
		return s
	}

	return strings.ReplaceAll(s, "`", "`+\"`\"+`")
}

var genHeaderPat = regexp.MustCompile(`// Code generated by .*; DO NOT EDIT\.`)

// isGenerated checks if the given file is a generated file by looking for the
// generated file header comment [https://go.dev/blog/generate].
func isGenerated(file *ast.File) bool {
	if file.Comments == nil {
		return false
	}

	if len(file.Comments) == 0 {
		return false
	}

	firstComment := file.Comments[0]
	if firstComment == nil || len(firstComment.List) == 0 {
		return false
	}

	if genHeaderPat.MatchString(firstComment.List[0].Text) {
		return true
	}

	return false
}

// prettyPrintValidationErr formats a validation error with its location,
// highlighting the relevant code in the source file.
func prettyPrintValidationErr(fset *token.FileSet, verr godogen.Error) string {
	location := fset.Position(verr.Pos())
	lineNr := location.Line

	file, err := os.Open(fset.File(verr.Pos()).Name())
	if err != nil {
		// fallback
		return fmt.Sprintf("%s: %s", location, verr.Message)
	}

	lineOffset, line, err := getLine(file, lineNr)
	if err != nil {
		// fallback
		return fmt.Sprintf("%s: %s", location, verr.Message)
	}

	nodeOffset := fset.File(verr.Pos()).Offset(verr.Pos())
	nodeOffsetEnd := fset.File(verr.End()).Offset(verr.End())

	inLineOffset := nodeOffset - lineOffset
	inLineLen := slices.Min([]int{len(line) - inLineOffset, nodeOffsetEnd - nodeOffset})

	return fmt.Sprintf("%s: %s\n%s\n%s%s",
		location, verr.Message,
		line,
		strings.Repeat(" ", inLineOffset), strings.Repeat("^", inLineLen),
	)
}

// getLine return the nth line of the file, along with its offset in the file.
func getLine(file *os.File, line int) (int, string, error) {
	r := bufio.NewReader(file)
	offset := 0

	for i := range line {
		// Read until newline or EOF
		content, err := r.ReadBytes('\n')
		if err != nil {
			return 0, "", err
		}

		if i == line-1 {
			return offset, strings.TrimRight(string(content), "\r\n"), nil
		}

		offset += len(content)
	}

	return 0, "", fmt.Errorf("line %d not found in file", line)
}

// setupLogger configures the logger, if verbose is true, it sets the log level to debug.
func setupLogger(verbose bool) {
	level := slog.LevelInfo
	if verbose {
		level = slog.LevelDebug
	}

	slog.SetDefault(slog.New(slog.NewJSONHandler(os.Stderr, &slog.HandlerOptions{
		Level: level,
	})))
}
