Feature: Function Signatures
  As a developer using godogen
  I want to use various valid function signatures
  So that I can write flexible step definitions

  Scenario: Function returning error only
    Given a Go file "steps.go" with content:
      """go
      package example

      //godogen:given ^I have cucumbers$
      func (s *Suite) step() error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have cucumbers$`, r1.step)
      }
      """

  Scenario: Function with context.Context first param
    Given a Go file "steps.go" with content:
      """go
      package example

      import "context"

      //godogen:given ^I have cucumbers$
      func (s *Suite) step(ctx context.Context) error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have cucumbers$`, r1.step)
      }
      """

  Scenario: Function with int param
    Given a Go file "steps.go" with content:
      """go
      package example

      //godogen:given ^I have (\d+) cucumbers$
      func (s *Suite) step(count int) error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have (\d+) cucumbers$`, r1.step)
      }
      """

  Scenario: Function with string param
    Given a Go file "steps.go" with content:
      """go
      package example

      //godogen:given ^I have "([^"]*)" cucumbers$
      func (s *Suite) step(name string) error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have "([^"]*)" cucumbers$`, r1.step)
      }
      """

  Scenario: Function with godog.Table param
    Given a Go file "steps.go" with content:
      """go
      package example

      import "github.com/cucumber/godog"

      //godogen:given ^I have the following items:$
      func (s *Suite) step(table *godog.Table) error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have the following items:$`, r1.step)
      }
      """

  Scenario: Function with context and multiple params
    Given a Go file "steps.go" with content:
      """go
      package example

      import "context"

      //godogen:given ^I have (\d+) "([^"]*)" items$
      func (s *Suite) step(ctx context.Context, count int, name string) error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have (\d+) "([^"]*)" items$`, r1.step)
      }
      """

  Scenario: Function returning context and error
    Given a Go file "steps.go" with content:
      """go
      package example

      import "context"

      //godogen:given ^I have cucumbers$
      func (s *Suite) step(ctx context.Context) (context.Context, error) {
          return ctx, nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have cucumbers$`, r1.step)
      }
      """

  Scenario: Void function with no params
    Given a Go file "steps.go" with content:
      """go
      package example

      //godogen:given ^I have cucumbers$
      func (s *Suite) step() {
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have cucumbers$`, r1.step)
      }
      """

  Scenario: Function without receiver
    Given a Go file "steps.go" with content:
      """go
      package example

      //godogen:given ^I have (\d+) cucumbers$
      func iHaveCucumbers(count int) error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have (\d+) cucumbers$`, iHaveCucumbers)
      }
      """
