Feature: Generic Receivers
  As a developer using godogen
  I want to use generic context structs as receivers
  So that I can share type-safe state across step definitions

  Scenario: Single generic receiver with any constraint
    Given a Go file "steps.go" with content:
      """go
      package example

      type ScState[T any] struct{ data T }

      //godogen:when ^I want to use methods$
      func (*ScState[T]) NowWithMethods() {}
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps[T1 any](sc *godog.ScenarioContext, r1 *ScState[T1]) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.When(`^I want to use methods$`, r1.NowWithMethods)
      }
      """

  Scenario: Multiple generic receivers with different type parameters
    Given a Go file "steps.go" with content:
      """go
      package example

      type ScState[T any] struct{ data T }
      type ScState2[U comparable] struct{ data U }

      //godogen:when ^pattern one$
      func (*ScState[T]) Method1() {}

      //godogen:when ^pattern two$
      func (*ScState2[U]) Method2() {}
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps[T1 any, T2 comparable](sc *godog.ScenarioContext, r1 *ScState[T1], r2 *ScState2[T2]) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.When(`^pattern one$`, r1.Method1)
      	sc.When(`^pattern two$`, r2.Method2)
      }
      """

  Scenario: Mixed generic and non-generic receivers
    Given a Go file "steps.go" with content:
      """go
      package example

      type GenericState[T any] struct{ data T }
      type PlainState struct{}

      //godogen:when ^generic step$
      func (*GenericState[T]) GenericMethod() {}

      //godogen:when ^plain step$
      func (*PlainState) PlainMethod() {}
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps[T1 any](sc *godog.ScenarioContext, r1 *GenericState[T1], r2 *PlainState) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.When(`^generic step$`, r1.GenericMethod)
      	sc.When(`^plain step$`, r2.PlainMethod)
      }
      """

  Scenario: Generic receiver with multiple type parameters
    Given a Go file "steps.go" with content:
      """go
      package example

      type ScState[K comparable, V any] struct{ data map[K]V }

      //godogen:when ^I use multi-param generics$
      func (*ScState[K, V]) Method() {}
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps[T1 comparable, T2 any](sc *godog.ScenarioContext, r1 *ScState[T1, T2]) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.When(`^I use multi-param generics$`, r1.Method)
      }
      """
