Feature: Hook Directives
  As a developer using godogen
  I want to generate hook registration code from godogen directives
  So that I can set up and tear down test state

  Scenario: Generate before hook
    Given a Go file "hooks.go" with content:
      """
      package example

      import "context"

      //godogen:before
      func (s *Suite) beforeScenario(ctx context.Context) (context.Context, error) {
          return ctx, nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "hooks_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeHooks registers steps defined in "hooks.go" with the [godog.ScenarioContext].
      func InitializeHooks(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Before(r1.beforeScenario)
      }
      """

  Scenario: Generate after hook
    Given a Go file "hooks.go" with content:
      """
      package example

      import "context"

      //godogen:after
      func (s *Suite) afterScenario(ctx context.Context) (context.Context, error) {
          return ctx, nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "hooks_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeHooks registers steps defined in "hooks.go" with the [godog.ScenarioContext].
      func InitializeHooks(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.After(r1.afterScenario)
      }
      """

  Scenario: Generate before_step hook
    Given a Go file "hooks.go" with content:
      """
      package example

      import "context"

      //godogen:before_step
      func (s *Suite) beforeStep(ctx context.Context) (context.Context, error) {
          return ctx, nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "hooks_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeHooks registers steps defined in "hooks.go" with the [godog.ScenarioContext].
      func InitializeHooks(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.StepContext().Before(r1.beforeStep)
      }
      """

  Scenario: Generate after_step hook
    Given a Go file "hooks.go" with content:
      """
      package example

      import "context"

      //godogen:after_step
      func (s *Suite) afterStep(ctx context.Context) (context.Context, error) {
          return ctx, nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "hooks_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeHooks registers steps defined in "hooks.go" with the [godog.ScenarioContext].
      func InitializeHooks(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.StepContext().After(r1.afterStep)
      }
      """

  Scenario: Multiple hooks in same file
    Given a Go file "hooks.go" with content:
      """
      package example

      import "context"

      //godogen:before
      func (s *Suite) setup(ctx context.Context) (context.Context, error) {
          return ctx, nil
      }

      //godogen:after
      func (s *Suite) teardown(ctx context.Context) (context.Context, error) {
          return ctx, nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "hooks_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeHooks registers steps defined in "hooks.go" with the [godog.ScenarioContext].
      func InitializeHooks(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Before(r1.setup)
      	sc.After(r1.teardown)
      }
      """
