Feature: Multiple Patterns
  As a developer using godogen
  I want to use multiple directives on the same function
  So that I can reuse step implementations for similar patterns

  Scenario: Multiple given directives on same function
    Given a Go file "steps.go" with content:
      """go
      package example

      //godogen:given ^I have (\d+) cucumbers$
      //godogen:given ^there are (\d+) cucumbers$
      func (s *Suite) cucumbersExist(count int) error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have (\d+) cucumbers$`, r1.cucumbersExist)
      	sc.Given(`^there are (\d+) cucumbers$`, r1.cucumbersExist)
      }
      """

  Scenario: Mixed directive types on same function
    Given a Go file "steps.go" with content:
      """go
      package example

      //godogen:given ^I have (\d+) items$
      //godogen:when ^I add (\d+) items$
      func (s *Suite) setItems(count int) error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have (\d+) items$`, r1.setItems)
      	sc.When(`^I add (\d+) items$`, r1.setItems)
      }
      """

  Scenario: Step directive with given directive on same function
    Given a Go file "steps.go" with content:
      """go
      package example

      //godogen:step ^I have (\d+) things$
      //godogen:given ^there are (\d+) things$
      func (s *Suite) thingsExist(count int) error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Step(`^I have (\d+) things$`, r1.thingsExist)
      	sc.Given(`^there are (\d+) things$`, r1.thingsExist)
      }
      """
