Feature: Multi-File Support
  As a developer using godogen
  I want to organize steps across multiple files
  So that I can maintain a clean codebase

  Scenario: Single file in directory
    Given a Go file "steps.go" with content:
      """go
      package example

      //godogen:given ^I have cucumbers$
      func (s *Suite) step() error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have cucumbers$`, r1.step)
      }
      """

  Scenario: Multiple files in directory
    Given a Go file "given_steps.go" with content:
      """go
      package example

      //godogen:given ^I have cucumbers$
      func (s *Suite) givenStep() error {
          return nil
      }
      """
    And a Go file "when_steps.go" with content:
      """go
      package example

      //godogen:when ^I eat cucumbers$
      func (s *Suite) whenStep() error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "given_steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeGivenSteps registers steps defined in "given_steps.go" with the [godog.ScenarioContext].
      func InitializeGivenSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have cucumbers$`, r1.givenStep)
      }
      """
    And the file "when_steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeWhenSteps registers steps defined in "when_steps.go" with the [godog.ScenarioContext].
      func InitializeWhenSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.When(`^I eat cucumbers$`, r1.whenStep)
      }
      """

  Scenario: Multiple receiver types across files
    Given a Go file "suite_steps.go" with content:
      """go
      package example

      type Suite struct{}

      //godogen:given ^I have cucumbers$
      func (s *Suite) suiteStep() error {
          return nil
      }
      """
    And a Go file "context_steps.go" with content:
      """go
      package example

      type TestContext struct{}

      //godogen:when ^I eat cucumbers$
      func (tc *TestContext) contextStep() error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "suite_steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSuiteSteps registers steps defined in "suite_steps.go" with the [godog.ScenarioContext].
      func InitializeSuiteSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have cucumbers$`, r1.suiteStep)
      }
      """
    And the file "context_steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeContextSteps registers steps defined in "context_steps.go" with the [godog.ScenarioContext].
      func InitializeContextSteps(sc *godog.ScenarioContext, r1 *TestContext) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.When(`^I eat cucumbers$`, r1.contextStep)
      }
      """

  Scenario: Multiple receiver types in same file
    Given a Go file "steps.go" with content:
      """go
      package example

      type Suite struct{}
      type TestContext struct{}

      //godogen:given ^I have cucumbers$
      func (s *Suite) suiteStep() error {
          return nil
      }

      //godogen:when ^I eat cucumbers$
      func (tc *TestContext) contextStep() error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite, r2 *TestContext) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have cucumbers$`, r1.suiteStep)
      	sc.When(`^I eat cucumbers$`, r2.contextStep)
      }
      """
