Feature: Skip Generated Files
  As a developer using godogen
  I want generated files to be skipped during processing
  So that I don't get duplicate registrations

  Scenario: Skip files with generated header
    Given a Go file "steps.go" with content:
      """go
      package example

      //godogen:given ^I have cucumbers$
      func (s *Suite) step() error {
          return nil
      }
      """
    And a Go file "old_generated.go" with content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      //godogen:given ^I have tomatoes$
      func (s *Suite) oldStep() error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have cucumbers$`, r1.step)
      }
      """
    And the file "old_generated_initialize.go" should not exist

  Scenario: Skip files with go generate header
    Given a Go file "steps.go" with content:
      """go
      package example

      //godogen:given ^I have cucumbers$
      func (s *Suite) step() error {
          return nil
      }
      """
    And a Go file "generated_by_other.go" with content:
      """go
      // Code generated by other-tool; DO NOT EDIT.

      package example

      //godogen:given ^I have tomatoes$
      func (s *Suite) otherStep() error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """go
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have cucumbers$`, r1.step)
      }
      """
    And the file "generated_by_other_initialize.go" should not exist
