Feature: Step Directives
  As a developer using godogen
  I want to generate step registration code from godogen directives
  So that I can easily wire up my BDD step definitions

  Scenario: Generate step initializer from godogen:given directive
    Given a Go file "steps.go" with content:
      """go
      package example

      //godogen:given ^I have (\d+) cucumbers$
      func (s *Suite) iHaveCucumbers(count int) error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the command output should be empty
    And the file "steps_initialize.go" should have content:
      """gogo
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Given(`^I have (\d+) cucumbers$`, r1.iHaveCucumbers)
      }
      """

  Scenario: Generate step initializer from godogen:when directive
    Given a Go file "steps.go" with content:
      """go
      package example

      //godogen:when ^I eat (\d+) cucumbers$
      func (s *Suite) iEatCucumbers(count int) error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """gogo
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.When(`^I eat (\d+) cucumbers$`, r1.iEatCucumbers)
      }
      """

  Scenario: Generate step initializer from godogen:then directive
    Given a Go file "steps.go" with content:
      """go
      package example

      //godogen:then ^I should have (\d+) cucumbers$
      func (s *Suite) iShouldHaveCucumbers(count int) error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """gogo
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Then(`^I should have (\d+) cucumbers$`, r1.iShouldHaveCucumbers)
      }
      """

  Scenario: Generate step initializer from godogen:step directive
    Given a Go file "steps.go" with content:
      """go
      package example

      //godogen:step ^I have (\d+) cucumbers$
      func (s *Suite) iHaveCucumbers(count int) error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should have content:
      """gogo
      // Code generated by godogen; DO NOT EDIT.

      package example

      import "github.com/cucumber/godog"

      // InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
      func InitializeSteps(sc *godog.ScenarioContext, r1 *Suite) {
      	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
      	// of the respective function declaration.
      	//
      	// Note: there must be no space between the "//" and the "godogen:step",
      	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
      	sc.Step(`^I have (\d+) cucumbers$`, r1.iHaveCucumbers)
      }
      """

  Scenario: Directive types are case-sensitive
    Given a Go file "steps.go" with content:
      """go
      package example

      //godogen:GIVEN ^I have cucumbers$
      func (s *Suite) iHaveCucumbers() error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should not exist
    And the command output should contain "unknown directive"

  Scenario: Ignore comment with space after slashes
    Given a Go file "steps.go" with content:
      """go
      package example

      // godogen:given ^I have cucumbers$
      func (s *Suite) iHaveCucumbers() error {
          return nil
      }
      """
    When I run godogen
    Then the command should succeed
    And the file "steps_initialize.go" should not exist
