// Code generated by godogen; DO NOT EDIT.

package indextest

import "github.com/cucumber/godog"

// InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
func InitializeSteps(sc *godog.ScenarioContext, r1 *TestContext) {
	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
	// of the respective function declaration.
	//
	// Note: there must be no space between the "//" and the "godogen:step",
	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
	sc.Given(`^(.+) is added to the workspace:$`, r1.AddFileToWorkspace)
	sc.Given(`^(.+) is added to the filesystem:$`, r1.AddFileToFilesystem)
	sc.When(`^I request step definitions for (.+) line (\d+)$`, r1.RequestStepDefinitions)
	sc.When(`^I request step references for (.+) line (\d+)()$`, r1.RequestStepReferences)
	sc.When(`^I request step references for (.+) line (\d+) column (\d+)$`, r1.RequestStepReferences)
	sc.Step(`^(.+) is updated on the filesystem:$`, r1.UpdateFileOnFilesystem)
	sc.Step(`^(.+) workspace version is removed$`, r1.RemoveWorkspaceVersion)
	sc.Then(`^I get (\d+) results?$`, r1.CheckResultCount)
	sc.Then(`^the results are:$`, r1.CheckResults)
	sc.Step(`^I request diagnostics for (.+)$`, r1.RequestDiagnostics)
	sc.Then(`^I get (\d+) diagnostics?$`, r1.CheckDiagnosticCount)
	sc.Then(`^diagnostic (\d+) message is "([^"]+)"$`, r1.CheckDiagnosticMessage)
	sc.Then(`^diagnostic (\d+) message contains "([^"]+)"$`, r1.CheckDiagnosticMessageContains)
	sc.When(`^I hover over line (\d+) column (\d+) in (.+)$`, r1.HoverOverPosition)
	sc.Then(`^I get hover content:$`, r1.CheckHoverContent)
	sc.Then(`^I get no hover content$`, r1.CheckNoHoverContent)
	sc.Then(`^diagnostic (\d+) message does not contain "([^"]+)"$`, r1.CheckDiagnosticMessageDoesNotContainVerbose)
	sc.Then(`^diagnostic (\d+) does not contain "([^"]+)"$`, r1.CheckDiagnosticMessageDoesNotContain)
	sc.Then(`^diagnostic (\d+) severity is "([^"]+)"$`, r1.CheckDiagnosticSeverity)
	sc.Then(`^diagnostic (\d+) is on line (\d+)$`, r1.CheckDiagnosticLine)
	sc.Then(`^diagnostic (\d+) has (\d+) related info$`, r1.CheckDiagnosticRelatedInfoCount)
	sc.Then(`^diagnostic (\d+) related info (\d+) is on line ()(\d+)$`, r1.CheckDiagnosticRelatedInfoLine)
	sc.Then(`^diagnostic (\d+) related info (\d+) is in file (.+) on line (\d+)$`, r1.CheckDiagnosticRelatedInfoLine)
	sc.When(`^I request document symbols for (.+) with hierarchy$`, r1.RequestDocumentSymbolsWithHierarchy)
	sc.When(`^I request document symbols for ([^ ]+)$`, r1.RequestDocumentSymbols)
	sc.Then(`^I get (\d+) symbols?$`, r1.CheckSymbolCount)
	sc.Then(`^symbol (\d+) name is "([^"]+)"$`, r1.CheckSymbolName)
	sc.Then(`^symbol (\d+) kind is "([^"]+)"$`, r1.CheckSymbolKind)
	sc.Then(`^symbol (\d+) is on line (\d+)$`, r1.CheckSymbolLine)
	sc.Then(`^symbol (\d+) has (\d+) child(?:ren)?$`, r1.CheckSymbolChildCount)
	sc.Then(`^symbol (\d+) child (\d+) name is "([^"]+)"$`, r1.CheckSymbolChildName)
	sc.Then(`^symbol (\d+) child (\d+) kind is "([^"]+)"$`, r1.CheckSymbolChildKind)
}
