// Code generated by godogen; DO NOT EDIT.

package indextest

import "github.com/cucumber/godog"

// InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
func InitializeSteps(sc *godog.ScenarioContext, r1 *TestContext) {
	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
	// of the respective function declaration.
	//
	// Note: there must be no space between the "//" and the "godogen:step",
	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
	sc.When(`^(.+) is added to the workspace:$`, r1.AddFileToWorkspace)
	sc.When(`^(.+) is added to the filesystem:$`, r1.AddFileToFilesystem)
	sc.When(`^I request step definitions for (.+) line (\d+)$`, r1.RequestStepDefinitions)
	sc.When(`^I request step references for (.+) line (\d+)()$`, r1.RequestStepReferences)
	sc.When(`^I request step references for (.+) line (\d+) column (\d+)$`, r1.RequestStepReferences)
	sc.When(`^(.+) is updated on the filesystem:$`, r1.UpdateFileOnFilesystem)
	sc.When(`^(.+) workspace version is removed$`, r1.RemoveWorkspaceVersion)
	sc.Then(`^I get (\d+) results?$`, r1.CheckResultCount)
	sc.Then(`^the results are:$`, r1.CheckResults)
	sc.When(`^I request diagnostics for (.+)$`, r1.RequestDiagnostics)
	sc.Then(`^I get (\d+) diagnostics?$`, r1.CheckDiagnosticCount)
	sc.Then(`^diagnostic (\d+) message is "([^"]+)"$`, r1.CheckDiagnosticMessage)
	sc.Then(`^diagnostic (\d+) message contains "([^"]+)"$`, r1.CheckDiagnosticMessageContains)
}
