// Code generated by godogen; DO NOT EDIT.

package godogs

import "github.com/cucumber/godog"

// InitializeGodogSteps registers steps defined in "godog_steps.go" with the [godog.ScenarioContext].
func InitializeGodogSteps(sc *godog.ScenarioContext, r1 *ScState, r2 *ScState2) {
	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
	// of the respective function declaration.
	//
	// Note: there must be no space between the "//" and the "godogen:step",
	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
	sc.When(`^I want to use methods$`, r1.NowWithMethods)
	sc.Then(`^I can$`, r1.ThenICan)
	sc.Given(`^I need more than two state objects$`, r2.ItWorks)
	sc.Given(`there are (\d+) godogs`, thereAreGodogs)
	sc.When(`^I eat (\d+)$`, iEat)
	sc.When(`^I ingest (\d+)$`, iEat)
	sc.Then(`^there should be (\d+) remaining$`, thereShouldBeRemaining)
	sc.Step(`^there should be none remaining$`, thereShouldBeNoneRemaining)
	sc.Before(resetGodogs)
	sc.StepContext().Before(printStep)
}
