// Code generated by godogen; DO NOT EDIT.

package fsystest

import "github.com/cucumber/godog"

// InitializeSteps registers steps defined in "steps.go" with the [godog.ScenarioContext].
func InitializeSteps(sc *godog.ScenarioContext, r1 *TestContext) {
	// DO NOT EDIT, instead edit the "//godogen:step <PATTERN>" directive
	// of the respective function declaration.
	//
	// Note: there must be no space between the "//" and the "godogen:step",
	// see "directive comment" in https://tip.golang.org/doc/comment#syntax
	sc.After(r1.cleanupAfterSceanrio)
	sc.Given(`^we watch pattern "([^"]+)"$`, r1.WatchPattern)
	sc.Given(`^file "([^"]+)" exists$`, r1.FileExists)
	sc.Given(`^directory "([^"]+)" exists$`, r1.DirectoryExists)
	sc.Given(`^discovery has run$`, r1.DiscoveryHasRun)
	sc.When(`^discovery runs$`, r1.DiscoveryRuns)
	sc.When(`^file "([^"]+)" is created$`, r1.FileIsCreated)
	sc.When(`^file "([^"]+)" is modified$`, r1.FileIsModified)
	sc.When(`^file "([^"]+)" is deleted$`, r1.FileIsDeleted)
	sc.When(`^directory "([^"]+)" is created$`, r1.DirectoryIsCreated)
	sc.When(`^directory "([^"]+)" is created with file "([^"]+)"$`, r1.DirectoryIsCreatedWithFile)
	sc.Then(`^"([^"]+)" should be indexed$`, r1.FileShouldBeIndexed)
	sc.Then(`^"([^"]+)" should not be indexed$`, r1.FileShouldNotBeIndexed)
	sc.Then(`^"([^"]+)" should be reindexed$`, r1.FileShouldBeReindexed)
	sc.Then(`^"([^"]+)" should be removed from index$`, r1.FileShouldBeRemovedFromIndex)
	sc.Then(`^directory "([^"]+)" should be watched$`, r1.DirectoryShouldBeWatched)
	sc.Then(`^directory "([^"]+)" should not be watched$`, r1.DirectoryShouldNotBeWatched)
}
